In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df= pd.read_csv("../Data/data.csv",
           index_col=0
           )

In [6]:
df

,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
m49_code,,,,,,,,,,,,,,,,,
104,Myanmar,NaN,23161.02,"Rice, milled",2015,1.78000,1.78%,26.12kgs,Storage,Storage,"30 days storage, with trapping",Rodents,NaN,Controlled Experiment,"Dr Steven Belmain (2015), context post-harvest...",NaN,Reference has been generated automatically
104,Myanmar,NaN,23161.02,"Rice, milled",2015,11.77000,11.77%,88.18kgs,Storage,Storage,"60 days storage, no trapping",Rodents,NaN,Controlled Experiment,"Dr Steven Belmain (2015), context post-harvest...",NaN,Reference has been generated automatically
104,Myanmar,NaN,23161.02,"Rice, milled",2015,5.88000,5.88%,44.09kgs,Storage,Storage,"30 days storage, no trapping",Rodents,NaN,Controlled Experiment,"Dr Steven Belmain (2015), context post-harvest...",NaN,Reference has been generated automatically
104,Myanmar,NaN,23161.02,"Rice, milled",2015,3.57000,3.57%,52.24kgs,Storage,Storage,"60 days storage, with trapping",Rodents,NaN,Controlled Experiment,"Dr Steven Belmain (2015), context post-harvest...",NaN,Reference has been generated automatically
104,Myanmar,NaN,23161.02,"Rice, milled",2015,17.65000,17.65%,132.27kgs,Storage,Storage,"90 days storage, no trapping",Rodents,NaN,Controlled Experiment,"Dr Steven Belmain (2015), context post-harvest...",NaN,Reference has been generated automatically
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,Zambia,NaN,0118,Millet,2000,2.50000,2.5,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN
894,Zambia,NaN,0118,Millet,2000,2.50000,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN
894,Zambia,NaN,0118,Millet,2000,2.38075,2.38075,NaN,Storage,Storage,NaN,NaN,NaN,Modelled Estimates,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN
894,Zambia,NaN,0118,Millet,2000,3.44008,3.44008,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN
894,Zambia,NaN,0118,Millet,2000,1.27433,1.27433,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN

In [7]:
df.country.unique()

array(['Myanmar', 'Burundi', 'Western Africa', 'Cambodia', 'Algeria',
       'Cameroon', 'Canada', 'Central Asia', 'Sri Lanka', 'Western Asia',
       'Chad', 'Northern Africa', 'Europe', 'Chile', 'China', 'Colombia',
       'Democratic Republic of the Congo', 'Costa Rica', 'Cuba', 'Africa',
       'Sub-Saharan Africa', 'Benin', 'Denmark', 'Northern America',
       'Ecuador', 'El Salvador', 'Ethiopia', 'Eritrea', 'Angola', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Palestine', 'Germany',
       'Ghana', 'Azerbaijan', 'Argentina', 'Guatemala', 'Guinea',
       'Guyana', 'Haiti', 'Southern Asia', 'Honduras',
       'South-Eastern Asia', 'India', 'Australia', 'Indonesia',
       'Iran (Islamic Republic of)', 'Italy', "Côte d'Ivoire",
       'Kazakhstan', 'Jordan', 'Kenya',
       "Democratic People's Republic of Korea", 'Republic of Korea',
       "Lao People's Democratic Republic",
       'Latin America and the Caribbean', 'Lebanon', 'Lesotho', 'Liberia',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Bahrain', 'Mexico', 'Bangladesh', 'Morocco', 'Mozambique',
       'Armenia', 'Oman', 'Namibia', 'Nepal', 'Australia and New Zealand',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines',
       'Guinea-Bissau', 'Timor-Leste', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Bolivia (Plurinational State of)', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Sierra Leone', 'Viet Nam', 'Somalia',
       'South Africa', 'Zimbabwe', 'Botswana', 'South Sudan', 'Sudan',
       'Eswatini', 'Sweden', 'Switzerland', 'Brazil',
       'Syrian Arab Republic', 'Thailand', 'Togo', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Uganda', 'Ukraine', 'Egypt',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Burkina Faso', 'Venezuela (Bolivarian Republic of)', 'Zambia'],
      dtype=object)